name: train-and-validate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      # Install Dagger CLI
      - name: Install Dagger CLI
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.20.3 sh
          sudo mv bin/dagger /usr/local/bin/dagger

      # Run Dagger pipeline (this starts the engine automatically)
      - name: Run Dagger pipeline
        run: go run dagger/main.go

      # Upload trained model for validator
      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: artifacts/model

      # Upload the full artifacts folder
      - name: Upload full artifacts bundle
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts

  validate:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: artifacts

      - name: Run model validator
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
        with:
          model-path: artifacts/model
